name: Container Patterns.com
email: Ben@ContainerPatterns.com
baseurl: "" 
permalink: /:title
url: "http://www.containerpatterns.com/"
twitter_username: containpatterns
layout: pattern

# Build settings
markdown: kramdown
